services:
  web:
    build: .
    container_name: fastapi
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - fastapi-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge
