name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
            set -e  # Exit if any command fails

            # Clone or Pull Latest Code
            if [ -d "hng12-fastapi-book-project" ]; then
              cd hng12-fastapi-book-project
              git fetch --all
              git reset --hard origin/main
            else
              git clone https://github.com/wathika-eng/hng12-fastapi-book-project && cd hng12-fastapi-book-project
            fi
                        
            docker-compose down
            docker-compose up --build -d

            # Clean Up Unused Resources
            docker system prune -af
          EOF
